### ISSUE TITLE
Support direct URL/links to app resources/actions such as Advanced Search, Layers, Manage etc.

### ISSUE THREAD

**Issue by rladines** [Chicago/opengrid#115]
Only focus on Shareable Queries for now -- not adv search, layers, manage, etc.

Link to a query and executing that link.

**Comment by tomschenkjr** [comment]
I agree. Can you mark #134 as duplicated and close it?

**Comment by tomschenkjr** [comment]
Have been using this on WindyGrid, but noticing some issue. Namely, issues are arising when sending the link because some programs are truncating the URL after the `#` symbol that are being used to define the colors.

For instance, [this link](https://webapps1.cityofchicago.org/windygrid/#/query?q=%7B%22name%22:%22Trap%20Map%20-%20Most%20Recent%202%22,%22owner%22:%22375492%22,%22spec%22:%5B%7B%22dataSetId%22:%22west_nile_virus%22,%22filters%22:%7B%22condition%22:%22AND%22,%22rules%22:%5B%7B%22id%22:%22when.collection_date%22,%22field%22:%22when.collection_date%22,%22type%22:%22date%22,%22input%22:%22text%22,%22operator%22:%22greater%22,%22value%22:%222%20weeks%20ago%22%7D,%7B%22id%22:%22what.total_true%22,%22field%22:%22what.total_true%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22greater%22,%22value%22:%220%22%7D%5D%7D,%22rendition%22:%7B%22color%22:%22#DC143C%22,%22opacity%22:%2285%22,%22size%22:%7B%22columnId%22:%22what.total_true%22,%22calculator%22:%22(Math.sqrt(@v)%20*%202.5)%20+%202%22%7D%7D%7D,%7B%22dataSetId%22:%22west_nile_virus%22,%22filters%22:%7B%22condition%22:%22AND%22,%22rules%22:%5B%7B%22id%22:%22when.collection_date%22,%22field%22:%22when.collection_date%22,%22type%22:%22date%22,%22input%22:%22text%22,%22operator%22:%22greater%22,%22value%22:%222%20weeks%20ago%22%7D%5D%7D,%22rendition%22:%7B%22color%22:%22#32CD32%22,%22opacity%22:%2285%22,%22size%22:%7B%22columnId%22:%22what.total_mosquitoes%22,%22calculator%22:%22(Math.sqrt(@v)%20*%202.5)%20+%202%22%7D%7D%7D%5D,%22sharedWith%22:%7B%22users%22:%5B%5D,%22groups%22:%5B%5D%7D,%22isCommon%22:false,%22autoRefresh%22:false,%22refreshInterval%22:%2230%22,%22_id%22:%7B%22$oid%22:%2259483d20e5eb0f137089c093%22%7D,%22geoFilter%22:%7B%22boundaryType%22:%22within%22,%22boundary%22:%22_map-extent%22%7D%7D&loc=41.80919639152055,-87.86659240722658,11&run=true&_=1232428846608) is being [truncated](https://webapps1.cityofchicago.org/windygrid/#/query?q=%7B%22name%22:%22Trap%20Map%20-%20Most%20Recent%202%22,%22owner%22:%22375492%22,%22spec%22:%5B%7B%22dataSetId%22:%22west_nile_virus%22,%22filters%22:%7B%22condition%22:%22AND%22,%22rules%22:%5B%7B%22id%22:%22when.collection_date%22,%22field%22:%22when.collection_date%22,%22type%22:%22date%22,%22input%22:%22text%22,%22operator%22:%22greater%22,%22value%22:%222%20weeks%20ago%22%7D,%7B%22id%22:%22what.total_true%22,%22field%22:%22what.total_true%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22greater%22,%22value%22:%220%22%7D%5D%7D,%22rendition%22:%7B%22color%22:%22) when embedding the link in a Microsoft Outlook email (e.g., inserting a link).

The hash/pound symbols aren't being encoded. However, when switching `#` to `%23`, the links are able to be shared and are also being properly interpreted by WG. 

Would it be possible to encode the `#` in the URL being generated by the application?

/cc @geneorama

**Comment by reve0716** [comment]
It works with newer version outlook and not with outlook desktop version 2010.

**Comment by tomschenkjr** [comment]
This should be expected. Outlook 2010 has a limit of 1033 characters<https://social.technet.microsoft.com/Forums/lync/en-US/bfbaf146-5f48-42cc-8172-41eb7be2e595/outlook-2010-what-is-the-character-limit-for-a-link-to-open?forum=outlook> in a link.

Please proceed with releasing the patch for this.

**Comment by tomschenkjr** [comment]
@nfspeedypur and @rladines - I see this issue is appearing in OpenGrid.io.

@rladines - did the patch you release in WindyGrid make it into the OpenGrid code or does that need to be ported?

**Comment by rladines** [comment]
It should be there. These are the commits that were part of that fix:
[Main.js](https://github.com/Chicago/opengrid/commit/91f66923990f7e2c8c477d8fb0473ade55743bcc)
[AdvancedSearch.js](https://github.com/Chicago/opengrid/commit/f723f909eee1f20d3232be46be9006b14876dc90)

@nfspeedypur Can you confirm that these were merged into  the OpenGrid.io code?

**Comment by tomschenkjr** [comment]
Ok, looks like I didn't do the test right on my end. Closing for now. Thanks everyone!

**Comment by tomschenkjr** [comment]
Re-opening this as I am seeing the bug pop-up. Here is a query that I generated from OpenGrid. There is a `#` appearing in the URL path.

https://chicago.opengrid.io/opengrid/#/query?q=%7B%22name%22:%22%22,%22owner%22:%22NoAuth%22,%22spec%22:%5B%7B%22dataSetId%22:%22food_inspections%22,%22filters%22:%7B%7D,%22rendition%22:%7B%22color%22:%22%252387CEEB%22,%22opacity%22:%2280%22,%22size%22:%226%22%7D%7D,%7B%22dataSetId%22:%22crimes_2001_to_present%22,%22filters%22:%7B%7D,%22rendition%22:%7B%22color%22:%22#FFD700%22,%22opacity%22:%2280%22,%22size%22:%226%22%7D%7D,%7B%22dataSetId%22:%22311_service_requests_graffiti_removal%22,%22filters%22:%7B%7D,%22rendition%22:%7B%22color%22:%22#6495ED%22,%22opacity%22:%2280%22,%22size%22:%226%22%7D%7D%5D,%22sharedWith%22:%7B%22users%22:%5B%5D,%22groups%22:%5B%5D%7D,%22isCommon%22:false,%22autoRefresh%22:false,%22refreshInterval%22:%2230%22,%22geoFilter%22:%7B%22boundaryType%22:%22near%22,%22boundary%22:%22_marker%22,%22value%22:%7B%22type%22:%22FeatureCollection%22,%22features%22:%5B%7B%22type%22:%22Feature%22,%22properties%22:%7B%7D,%22geometry%22:%7B%22type%22:%22Point%22,%22coordinates%22:%5B-87.62751102447511,41.877405938278116%5D%7D%7D%5D%7D,%22maxRadius%22:%22500%22,%22maxRadiusUnit%22:%22feet%22%7D%7D&run=true&_=361007470259

**Comment by tomschenkjr** [comment]
I haven't been able to replicate the bug in WindyGrid, even by using the same query.

**Comment by rladines** [comment]
@tomschenkjr was able to recreate this, even on the windygrid side. we had a bug where a single replace is done instead of global. should be fixed with branch [iss115](https://github.com/Chicago/opengrid/tree/iss115). I will submit a PR for the fix.

**Comment by tomschenkjr** [comment]
Closed by 8fe5094
