### ISSUE TITLE
Clearer build instructions please

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Chicago/opengrid#128]
I am trying to install OpenGrid, but so far I've failed to install it on my macbook pro.

Partially this is due to the `gulp release` or `gulp test` issues,  reported as #127 .

On the other hand I do not find the instruction very clear: I want to install a demo system to explore the art of the possible (and npm is not my main skill).

Could you kindly clarify how, after `gulp release`, I can get opengrid display on localhost:8080?

Many thanks

**Comment by rladines** [comment]
@smartinsightsfromdata Have you read this from the OpenGrid documentation? http://opengrid.readthedocs.org/en/latest/Installation%20and%20Setup/

The OpenGrid UI works with a service layer to provide its data. A template implementation of the service is referenced on the link above with more details on how to build and deploy it.

**Comment by tomschenkjr** [comment]
As discussed during our weekly meeting: we'll be moving the build instructions over to the [full documentation](http://opengrid.readthedocs.org), where we'll fully describe the build instructions for this repository and also the other services that are needed to build the project. We'll direct users from the README over to the full documentation to read those instructions, since README's strive to be pithy. Should help clarify the setup process.

**Comment by PriyaDoIT** [comment]
Closed.
