### ISSUE TITLE
Contribution instructions unclear

### ISSUE THREAD

**Issue by EricTendian** [Chicago/opengrid#130]
Couple issues I found while reading through [CONTRIBUTING.md](https://github.com/Chicago/opengrid/blob/master/CONTRIBUTING.md):

- "Use the above link to sign the CLA with your GitHub credentials." but there is no link above that points to a place to sign the contributor license agreement.
- No `dev` branch in this repository (mentioned a couple times).
- The instruction "Build your changes locally to ensure all tests pass:" references `grunt test` but the project now uses `gulp`.
- Roadmap link is broken (points to https://github.com/Chicago/wiki/Roadmap at the moment).

I think these need to be addressed before anyone can successfully submit a pull request.

**Comment by tomschenkjr** [comment]
The CLA should be enforced by [CLA Hub](www.clahub.com). But it's still valid. I've updated the doc to remove reference to signature since it's integrated into the pull request workflow.

We've paused on a grand roadmap, so will point to the other planning documentation (which has similar content).

Changed the `grunt` to `gulp`.

Developed a dev branch based on all of these changes.

**Comment by EricTendian** [comment]
@tomschenkjr thanks! The changes you made clear that up.
