### ISSUE TITLE
Sort the datasets under Add Dataset

### ISSUE THREAD

**Issue by levyj** [Chicago/opengrid#141]
As datasets are added, this may become important to finding the desired dataset.

**Comment by tomschenkjr** [comment]
@dianaclem - wasn't @rladines also working on this for the v1.1.0 milestone? It was mentioned in a meeting a couple of weeks ago.

**Comment by dianaclem** [comment]
Mentioned by Uturn for OpenGrid.io<http://opengrid.io>.   Rod, correct me if wrong or elaborate.

Get Outlook for iOS<https://aka.ms/o0ukef>




On Sat, May 21, 2016 at 12:33 PM -0700, "Tom Schenk Jr" <notifications@github.com<mailto:notifications@github.com>> wrote:


@dianaclem<https://github.com/dianaclem> - wasn't @rladines<https://github.com/rladines> also working on this for the v1.1.0 milestone? It was mentioned in a meeting a couple of weeks ago.

-

**Comment by smarziano** [comment]
I was going to add this issue because it was one of my recommendations from the CUTGroup test. Not sure if it is completed because it's not on production:

<img width="454" alt="screen shot 2016-06-19 at 9 16 55 am" src="https://cloud.githubusercontent.com/assets/5550969/16177888/ac35f9bc-35fe-11e6-93c3-d8d247693792.png">
