### ISSUE TITLE
Add the ability to add a dataset based on the 4x4 of the underlying dataset

### ISSUE THREAD

**Issue by levyj** [Chicago/opengrid#143]
This one may be a bit iffy but I can imagine situations where someone knows the 4x4 of the underlying dataset so why not let him/her use that?  This could be particularly useful for various use cases through the API instead of the Web UI,

**Comment by tomschenkjr** [comment]
This might fall more under Plenario than opengrid since we're relying on that to pull in the data portal data. I don't think the Plenario API surfaces that to us.


Tom Schenk Jr.

Chief Data Officer

Department of Innovation and Technology

City of Chicago

(312) 744-2770

tom.schenk@cityofchicago.org

data.cityofchicago.org


________________________________

**Comment by levyj** [comment]
Got it.  I was thinking there might be a place to add metadata when we accept a Plenario dataset into Opengrid.

https://github.com/UrbanCCD-UChicago/plenario/issues/203 might be relevant, if accepted.
