### ISSUE TITLE
Images in /docs/media slow down clone

### ISSUE THREAD

**Issue by WillEngler** [Chicago/opengrid#145]
A friendly suggestion for the Chicago dev team:

My initial `git clone` took a few minutes because the total download size was ~180 MB. Unless I'm missing something, the images in /docs/media aren't anywhere on the site, but they contribute about 96 MB to the total repo size. Moving those out of the repo could be a quick way to remove an annoyance for potential contributors.

**Comment by tomschenkjr** [comment]
@WillEngler - finally took a look at this. I do see that `/docs/meda` file, which contains the screenshots for the [documentation](opengrid.readthedocs.org). A quick check is about 96MB for that folder.

But, they're PNG, so these are uncompressed files and takes-up too much space. 

@reve0716 -- we may want to consider moving these to `.jpg`. See if there is an image converter to move the files to jpg (and then update documentation to .jpg instead of .png extensions.

**Comment by PriyaDoIT** [comment]
Rod to push to production.

**Comment by tomschenkjr** [comment]
@reve0716 - `combine33.jpg` seems to be missing and the HTML needs to be updated as well
