### ISSUE TITLE
Environmental Permits, Environmental Inspections not displaying correctly

### ISSUE THREAD

**Issue by tomschenkjr** [Chicago/opengrid#202]
When running a query in OpenGrid, "environmental" data is incorrectly mapping everything at (-1,-1). 
![image](https://cloud.githubusercontent.com/assets/1639121/15492864/58421a02-2145-11e6-82b3-33d0638a4c55.png)

However, the data in the Open Data Portal seems correct:
![image](https://cloud.githubusercontent.com/assets/1639121/15492869/69d458c0-2145-11e6-95d3-52b3562a57f9.png)

Likewise, Plenario appears to be displaying correctly:
![image](https://cloud.githubusercontent.com/assets/1639121/15492885/939f2d92-2145-11e6-8ea3-5ba3b94b8593.png)

Thus, seems like it's something wrong specific to OpenGrid.

(cc @levyj)

**Comment by levyj** [comment]
@willengler - I just noticed that the dataset API Field Name for the Location column in https://data.cityofchicago.org/Environment-Sustainable-Development/CDPH-Environmental-Permits/ir7v-8mc8 (MAPPED LOCATION) is **location_1**.  Does Plenario rely on the Location column in a dataset always being **location**?

**Comment by WillEngler** [comment]
@levyj No, it does not. The name of the column location column is a piece of metadata we require on dataset submission. Checking in the admin panel, this is what we have for Environmental Permits
<img width="1426" alt="screen shot 2016-05-27 at 1 48 24 pm" src="https://cloud.githubusercontent.com/assets/6283143/15618076/d61d9a18-2411-11e6-8015-f6a2f7e76e59.png">

**Comment by levyj** [comment]
Ok. Just a thought. Can you confirm whether you get any garbage location values -- text, instead of lat/long? I think the Socrata API filters them out but was trying to think through possible reasons for the OpenGrid problem.



On Fri, May 27, 2016 at 11:49 AM -0700, "Will Engler" <notifications@github.com<mailto:notifications@github.com>> wrote:


@levyj<https://github.com/levyj> No, it does not. The name of the column location column is a piece of metadata we require on dataset submission. Checking in the admin panel, this is what we have for Environmental Permits
[screen shot 2016-05-27 at 1 48 24 pm]<https://cloud.githubusercontent.com/assets/6283143/15618076/d61d9a18-2411-11e6-8015-f6a2f7e76e59.png>

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Chicago/opengrid/issues/202#issuecomment-222225227>, or mute the thread<https://github.com/notifications/unsubscribe/AFQ6V9Jn-kXzOxA7n1ARTSlLr02ZhTVkks5qFzzIgaJpZM4IlHhT>.


________________________________
This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. If you are not the intended recipient of this e-mail (or the person responsible for delivering this document to the intended recipient), you are hereby notified that any dissemination, distribution, printing or copying of this e-mail, and any attachment thereto, is strictly prohibited. If you have received this e-mail in error, please respond to the individual sending the message, and permanently delete the original and any copy of any e-mail and printout thereof.

**Comment by WillEngler** [comment]
So, looking a little deeper, we do indeed get some garbage values (17098, to be exact). The ones with just text get interpreted as a NULL geom by Plenario's ETL. IIRC, OpenGrid always queries Plenario with a boundary around Chicago. That should mean that none of the records with text-only locations get returned by the query, because a null geom is not included in any box. 

If possible, it would be great to see the data OpenGrid is receiving from Plenario to see if there's anything fishy. If I recall correctly, it's a call to /detail?dataset_name=<name>. I gave that a go and mapped it, and didn't see any red flags.
<img width="288" alt="screen shot 2016-05-27 at 4 00 10 pm" src="https://cloud.githubusercontent.com/assets/6283143/15621131/5c03dfb8-2424-11e6-9b6f-881cc8cccda2.png">

**Comment by tomschenkjr** [comment]
@PriyaDoIT and @dianaclem pointed this out to me:

It appears that 

Jon, can you tell if the `LOCATION_1` column is being geocoded by us or Socrata? Perhaps it's the latter which is causing the issue?

![image](https://cloud.githubusercontent.com/assets/1639121/15623707/5a645f98-243d-11e6-9398-de410a3f1de5.png)

**Comment by levyj** [comment]
I think it is being geocoded by Socrata, although that should switch to us when we migrate the ETL to Kettle.  I am not sure that would matter -- although maybe -- but location_1 (Human Readable: MAPPED LOCATION) does get the street address, which I think still lives in the column along with the geocoded lat/long.  Generally, our location columns _only_ have lat/long.  I do not think that makes too big a difference but wanted to mention it.

**Comment by tomschenkjr** [comment]
Ok, good to know.

I actually think the API is passing along the street address (see the screenshot from OpenGrid above). So, OpenGrid can’t figure out how to display it since it’s trying to display a string.

**Comment by WillEngler** [comment]
Following up on today's dev call, I misspoke about the source of column names in Plenario. 

Good news: It _used to be the case_ that we unconditionally grabbed the head of a CSV to determine column names. I have since deployed a change that gets it from the Socrata API.

Bad news: To stay consistent with the old style, I have it rigged to grab the `name` attribute (which goes at the top of the CSV), not the `fieldName` attribute (used for the SODA API). If this is causing havoc, I wouldn't see any harm in using `fieldName` instead. We could then re-import datasets that had a mismatch.

**Comment by WillEngler** [comment]
Following up on conversation in the 6/10/16 meeting, this is how Plenario parses latitude and longitude:

```SQL
CREATE OR REPLACE FUNCTION point_from_loc(loc text)
    RETURNS geometry(Point,4326)
AS
$$
SELECT ST_PointFromText('POINT(' || subq.longitude || ' ' || subq.latitude || ')', 4326)
FROM ( SELECT FLOAT8((regexp_matches($1, '\((.*),.*\)'))[1]) AS latitude,
              FLOAT8((regexp_matches($1, '\(.*,(.*)\)'))[1]) AS longitude) as subq;
$$
LANGUAGE 'sql' IMMUTABLE;
```

The regex finds a (lon, lat) pair anywhere in a string, so that's why we're still able to extract geometry from cells like '<some address> (lon, lat)'
