### ISSUE TITLE
BASE MAP

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#204]
**From WG Issue 60054**

Even after adjusting the opacity of the dots to 100, the colors are still too light against the base street map and aerial map. Suggest non-pastel colors for dots to increase contrast with base map. 

The base street map is very unattractive. Using gray instead of off-yellow for the street areas would be preferable (See Google Maps or Bing Maps). 

Also the font used for street names is not clear. Once again the font used in Google Maps or Bing Maps is much clearer. 

In addition to the street and aerial base maps, an oblique aerial angle (bird’s eye) and street view options would also be greatly helpful. 

----------------------------------------------------------------------------------------------
Tom Schenk – We have a few options that we can try: 

```javascript
// Esri.WorldGrayCanvas -- a neutral basemap with ESRI labeling 
// https: also suppported. 
var Esri_WorldGrayCanvas = L.tileLayer('http://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}';;, { 
attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ', 
maxZoom: 16 
}); 

// CartoDB Positron -- another neutral background with better labelling at higher zoom levels 
var CartoDB_Positron = L.tileLayer('http://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png', { 
attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://cartodb.com/attributions">CartoDB</a>';;, 
subdomains: 'abcd', 
maxZoom: 19 
}); 

// OpenMap Grayscale with Stamen Labels -- light background with heavier labelling 
var OpenMapSurfer_Grayscale = L.tileLayer('http://korona.geog.uni-heidelberg.de/tiles/roadsg/x={x}&y={y}&z={z}';;, { 
maxZoom: 19, 
attribution: 'Imagery from <a href="http://giscience.uni-hd.de/">GIScience Research Group @ University of Heidelberg</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>';; 
}); 
// https: also suppported. 
var Stamen_TonerLabels = L.tileLayer('http://stamen-tiles-{s}.a.ssl.fastly.net/toner-labels/{z}/{x}/{y}.{ext}', { 
attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a> &mdash; Map data &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>';;, 
subdomains: 'abcd', 
minZoom: 0, 
maxZoom: 20, 
ext: 'png' 
}); 

// CartoDB Dark background -- may offer more contrast for some colors 
var CartoDB_DarkMatter = L.tileLayer('http://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}.png', { 
attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://cartodb.com/attributions">CartoDB</a>';;, 
subdomains: 'abcd', 
maxZoom: 19
```

**Comment by WillEngler** [comment]
FWIW I've been looking around at new base maps for Plenario and I fell in love with CartoDB Positron. It feels so crisp at the high zoom our users are usually poking around in. (Haven't swapped it in yet, but soon.)

**Comment by tomschenkjr** [comment]
For others, you can preview these layers at https://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by PriyaDoIT** [comment]
@tomschenkjr , I like Thunderforest.Transport and OpenMaySurfer.Roads, the CartoDB Positron ones look good too, but I am not sure if they have specialized names for each style.

**Comment by tomschenkjr** [comment]
@Chicago/open-gov-team - just a reminder everyone to get your input in for these maps.

**Comment by reve0716** [comment]
I have a small list that I think are cool (In order of preference)
Thunderforest.transport :+1: 
Thunderforest.landscape
Openstreetmap.Hot
Openstreetmap.France
Thunderforest.outdoors

**Comment by reve0716** [comment]
Diana and I have a few more that we think should be taken into consideration
OpenStreetMap.BlackandWhite
Mapbox
Hydda.Full

**Comment by tomschenkjr** [comment]
One note on OpenStreetMap – this will use roads and namings as assigned from OpenStreetMap. I think this is risky. Our public safety folks care a lot about this and this might misalign with how they refer to streets.

The other two have more color around

@reve0716 – did you ever hear back from Peter on this opinions?

**Comment by reve0716** [comment]
I haven't heard anything back,Peter is on vacation til July 5 and his replacement contact that I CC'd in his place is not available any longer.

**Comment by tomschenkjr** [comment]
Got it. Thanks.

_
Tom Schenk Jr.
Chief Data Officer
Department of Innovation and Technology
City of Chicago
(312) 744-2770
tom.schenk@cityofchicago.org | @ChicagoCDO
data.cityofchicago.org | opengrid.io | digital.cityofchicago.org | chicago.github.io | dev.cityofchicago.org



On Fri, Jun 24, 2016 at 1:34 PM -0500, "Regina" <notifications@github.com<mailto:notifications@github.com>> wrote:


I haven't heard anything back,Peter is on vacation til July 5 and his replacement contact that I CC'd in his place is not available any longer.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/Chicago/opengrid/issues/204#issuecomment-228425164>, or mute the thread<https://github.com/notifications/unsubscribe/ABkC0bS2aKDAFg7SlloP028rakQsgKAsks5qPCMegaJpZM4Ir4tC>.


________________________________
This e-mail, and any attachments thereto, is intended only for use by the addressee(s) named herein and may contain legally privileged and/or confidential information. If you are not the intended recipient of this e-mail (or the person responsible for delivering this document to the intended recipient), you are hereby notified that any dissemination, distribution, printing or copying of this e-mail, and any attachment thereto, is strictly prohibited. If you have received this e-mail in error, please respond to the individual sending the message, and permanently delete the original and any copy of any e-mail and printout thereof.

**Comment by dianaclem** [comment]
Ready for retesting.    Go to WindyGrid Int environment.   We have put all the new base maps on the layer "base layers".      You may need to clear your cookies if they don't come up right away.  @PriyaDoIT @tomschenkjr @reve0716
