### ISSUE TITLE
Add way for users to color code their search results

### ISSUE THREAD

**Issue by smarziano** [Chicago/opengrid#215]
When a search result was completed, CUTGroup testers expected the results to be color coded based on differences in the data record. This also relates to issue #210.

As an example, for potholes reported in 60660, it would be an improvement if users could color code all "Potholes Patched" in one color and then "No Problem Found" in a different color. This would help them make some conclusions from the dataset they are seeing.
<img width="1277" alt="screen shot 2016-06-19 at 9 53 40 am" src="https://cloud.githubusercontent.com/assets/5550969/16178066/73803672-3604-11e6-8169-7c734c841c14.png">

**Comment by PriyaDoIT** [comment]
@tomschenkjr I think this could be fixed if we can have OG support OR filters.  The user could add two of the same datasets , 311 Service Requests - Pot Holes Reported, and have one with the filter most_Recent_Action = pothole filled with one color and another with most_Recent_Action = no pothole found with another color.

**Comment by tomschenkjr** [comment]
@PriyaDoIT - yeah, that makes sense.

**Comment by PriyaDoIT** [comment]
@tomschenkjr @smarziano 
Actually, we don't need OR for this.  It works for AND.  Since 311 data is iffy right now, I used the Food Inspections dataset twice.  One of them had a filter with facility type= School and the other facility type=Restaurant. Perhaps we can add this to the documentation.

![image](https://cloud.githubusercontent.com/assets/18470113/16209390/6b59492c-36fc-11e6-913f-e010760ec65b.png)

**Comment by PriyaDoIT** [comment]
Hi @reve0716 could you help update the documentation to add this information?  Here is what I wrote in a recent blog entry:
Sometimes we find that users want to differentiate the dot colors _within_ a dataset.  Using food establishments as an example, I want to find restaurants and food trucks in Chicago, both of these are listed under the single dataset, Business Licenses, but I want them represented on a map as two different colors.  What should I do since I can only add one color per dataset?  Simple, just add the Business Licensees dataset twice and set one with the filter License_description = “Retail Food Establishments” and the other License_description = “Mobile Food Licenses,” and assign each of them a different color.  In the example below, Retail Food Establishments are red and Mobile Food Licenses are blue. [I can send you the gif that I used to demonstrate this]
