### ISSUE TITLE
Support Bubbles on Map

### ISSUE THREAD

**Issue by PriyaDoIT** [Chicago/opengrid#239]
For an internal City of Chicago project, we have found that it would be helpful to display bubbles representing volume of an incidence for a particular area on a map.  We can utilize the size/color options that we have today and auto set the colors.

In the context of West Nile Virus:
    -  # of mosquitoes - blue
    - # positive for WNV in red
    - The size of the circles to auto size based on count of mosquitoes
    - Need to validate the circle for positive results (Gene)

example:
![image](https://cloud.githubusercontent.com/assets/18470113/19495590/989b6fae-9549-11e6-87a8-8b0733bd93b3.png)

Additional Considerations to discuss:
- Default Filters  may need to be implemented? still need to discuss this
      - week must equal the most recent week with data available AND season_year must equal the most recent year with data available OR
      - The map should display the most recent year and week with the data available with the grid view displaying all available data (assuming that the user doesn't specify any other time frames in the filter).

This functionality should be available for other datasets in the future as well.

**Comment by seancarroll** [comment]
Are you looking for Dorling Cartogram https://www.arcgis.com/home/item.html?id=b686a7679cb747e9825d1d1bb6b26046?

**Comment by tomschenkjr** [comment]
Those could be helpful, but more looking for bubbles that vary based on a numeric value associated with that data.

Consider, plotting the potholes in the city. It is useful to be able to plot the site of the circle to correspond to the number of potholes filled on the block. In the example below, the size of circle would be relatively larger

[cid:image001.png@01D207AF.5D675510]

**Comment by PriyaDoIT** [comment]
@tomschenkjr  can you reupload the image?  can't see it.

**Comment by geneorama** [comment]
The bubbles have been implemented, but there is an issue where they plot according to when the queries finish rather than the order indicated by when the data set was added.  
So, [this map](https://webapps1.cityofchicago.org/windygrid/#/query?q=%7B%22name%22:%22Trap%20Map%202016%20week%2031%22,%22owner%22:%22375492%22,%22spec%22:%5B%7B%22dataSetId%22:%22west_nile_virus%22,%22filters%22:%7B%22condition%22:%22AND%22,%22rules%22:%5B%7B%22id%22:%22what.season_year%22,%22field%22:%22what.season_year%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22equal%22,%22value%22:%222016%22%7D,%7B%22id%22:%22what.week%22,%22field%22:%22what.week%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22equal%22,%22value%22:%2231%22%7D,%7B%22id%22:%22what.total_true%22,%22field%22:%22what.total_true%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22greater%22,%22value%22:%220%22%7D%5D%7D,%22rendition%22:%7B%22color%22:%22#DC143C%22,%22opacity%22:%2285%22,%22size%22:%7B%22columnId%22:%22what.total_true%22,%22calculator%22:%22(Math.sqrt(@v)%20*%202.5)%20+%202%22%7D%7D%7D,%7B%22dataSetId%22:%22west_nile_virus%22,%22filters%22:%7B%22condition%22:%22AND%22,%22rules%22:%5B%7B%22id%22:%22what.season_year%22,%22field%22:%22what.season_year%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22equal%22,%22value%22:%222016%22%7D,%7B%22id%22:%22what.week%22,%22field%22:%22what.week%22,%22type%22:%22integer%22,%22input%22:%22text%22,%22operator%22:%22equal%22,%22value%22:%2231%22%7D%5D%7D,%22rendition%22:%7B%22color%22:%22#32CD32%22,%22opacity%22:%2285%22,%22size%22:%7B%22columnId%22:%22what.total_mosquitoes%22,%22calculator%22:%22(Math.sqrt(@v)%20*%202.5)%20+%202%22%7D%7D%7D%5D,%22sharedWith%22:%7B%22users%22:%5B%5D,%22groups%22:%5B%5D%7D,%22isCommon%22:false,%22autoRefresh%22:false,%22refreshInterval%22:%2230%22,%22_id%22:%7B%22$oid%22:%225942a273acf4d941c6cc98f2%22%7D,%22geoFilter%22:%7B%22boundaryType%22:%22within%22,%22boundary%22:%22_map-extent%22%7D%7D&loc=41.86137915587359,-87.69836425781251,11&run=true&_=763479891963) will sometimes render two different ways.
The intended way:
![image](https://user-images.githubusercontent.com/1392068/27659493-4dcebc28-5c19-11e7-847c-3e7b51fed4bf.png)

The unintended way: 
![image](https://user-images.githubusercontent.com/1392068/27659515-64e8e0dc-5c19-11e7-99ad-0227ae981685.png)

As a work around (thanks @rladines for showing me this) you can turn off the top layer then turn it back on, and it will appear on top.
