### ISSUE TITLE
Tile Map icon in the tablegrid

### ISSUE THREAD

**Issue by reve0716** [Chicago/opengrid#328]
The tile-map icon no longer available in the table grid. Is it a reason why it no longer shows in the table.

![2018-02-05_1551](https://user-images.githubusercontent.com/12734080/35830860-49e69fae-0a8d-11e8-9e5f-08aec9fbf4a5.png)

**Comment by reve0716** [comment]
@nfspeedypur will look into. Updates will be provided at Monday's meeting.

**Comment by tomschenkjr** [comment]
After discussing today, it was determined that the Tile Map is turned-off by default for OpenGrid. This was a configuration discussed in #194 and released in v1.3.0. It's likely this was done because of issues on determining the default tiles.

@reve0716 - please do some research in old and closed issues, as well as agendas, to confirm this.

**Comment by reve0716** [comment]
@rladines , Do you have any correspondence that supports this issue? I’ve check all my emails and the issues in OpenGrid and came up empty.
