### ISSUE TITLE
Is this site abandoned altogether?

### ISSUE THREAD

**Issue by alxfed** [Chicago/opengrid#337]
Hi,

I'm wondering whether you've abandoned this project altogether, or what?
The link to 'documentation' (under the question mark) leads to a broken page https://opengrid.readthedocs.io/en/latest/User%20Documentation, 
_nothing_ on the web-site works properly. Like LITERALLY **nothing**.

At the same time the map displays some datasets... somehow... I looked up the photocameras on traffic lights.

Once again, is there anybody in the house besides the 'CEO' who issues 'orders'? Is that you, Tom Schenk Jr.? Just wondering. Please respond.

Also, can you ping me at (alxfed at gmail dot com)? I have a question.

-Alex

**Comment by reve0716** [comment]
Hi Alxfed,
My name is Regina, I will take a look at this issue.

**Comment by alxfed** [comment]
Hi, Regina,
This is not THE issue that I want to be addressed. I was trying to find the API description and the instructions about the API keys. I clicked the "?" link and voila !

Thank you for answering. If you have any descriptions of your API I would appreciate if you'd have them emailed to my address above right away (before you fix the 'issue').

-Alex

**Comment by reve0716** [comment]
I'm assuming you're seeing the screen shot below as the broken page, if so please select the "Home" link it'll redirect you to the documentation page; from there scroll down and click on the API section. I hope this helps for now.

![image](https://user-images.githubusercontent.com/12734080/56509828-a2a10880-64ed-11e9-8b78-dcc9a2d8ba48.png)

**Comment by alxfed** [comment]
I did that a long time ago. Thank you. And yes, the page is broken.

I'm saying (see above) that there is nothing about the way for me to get an app token on this page of your manual https://opengrid.readthedocs.io/en/latest/system-administration/opengrid-api/

Is it the token that I have from https://data.cityofchicago.org/ ? Can you explain it to me or point at the page in you 'manual' explaining this?

**Comment by rladines** [comment]
@alxfed The disconnect is that the OpenGrid documentation site is pretty generic and is documenting the framework more than the API that the OpenGrid.IO website actually talks to.

If you look at this link:
https://opengrid.readthedocs.io/en/latest/system-administration/architecture/

there is a mention of a Plenar.io test service layer (URL is incorrect on the page, should be https://chicago.opengrid.io/opengrid-service/) which is the OpenGrid service implementation that wraps the [Plenar.io API](http://plenar.io/) but it was nowhere documented how to get a token for this specific service implementation.

The service is open but does require you to send specific credentials, initially since the framework requires this.

You can try this:
Request token by sending the following request:
URL: https://chicago.opengrid.io/opengrid-service/rest/users/token
METHOD: POST
Request Body:
```
{
  "username": "NoAuth",
  "password": "NoAuth"
}
```
You can then follow the OpenGrid documentation along. The key thing is sending **x-auth-token** on the header of sub-sequence requests.

Let me know if you need more help after this.

**Comment by alxfed** [comment]
Thank you, Rod. Will do.

P.S. Cute username/password; it's so useful to 'authenticate' everything that moves until it doesn't. Been there, done that. Not anymore.

**Comment by alxfed** [comment]
Rod, I'm sorry to disappoint you, but:

```
import requests

token = requests.post('https://chicago.opengrid.io/opengrid-service/rest/users/token', data = {"username": "NoAuth", "password": "NoAuth"})

print(r)
```
gives '<Response [500]>'

**Comment by alxfed** [comment]
<Response [500]>

**Comment by rladines** [comment]
@alxfed I did test the token call before I posted the comment yesterday. I think the problem was that the credentials are being sent on the header as part of basic authentication when it should be a JSON payload (in the request body).

I put together a quick JS Fiddle. Check out the link below. Pay particular attention to the Javascript code.
https://jsfiddle.net/shuret85/kfL5tg6c/45/

You should be able to do the same type of calls with the scripting language you're using.

**Comment by alxfed** [comment]
The issue is closed. Thank you.
